### PR TITLE
fix: Logic for retrying specifiied internal errors

### LINKED ISSUE #1808: Error: 13 INTERNAL: Received RST_STREAM not retried for Commit
The `Error: 13 INTERNAL: Received RST_STREAM` error is (probably) not retried for unary RPCs, such as `Commit`. It appears that the error is only retried for streaming read/executeSQL calls: https://github.com/googleapis/nodejs-spanner/blob/25ee7495369b8b75235c2a92450bc377dc2200cf/src/partial-result-stream.ts#L496

```
Error: 13 INTERNAL: Received RST_STREAM with code 1
    at Object.callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:190:52)
    at /app/node_modules/@grpc/grpc-js/build/src/call-stream.js:111:35
    at Object.onReceiveStatus (/app/node_modules/grpc-gcp/build/src/index.js:73:29)
    at InterceptingListenerImpl.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:106:23)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /app/node_modules/@grpc/grpc-js/build/src/call-stream.js:188:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/app/node_modules/@grpc/grpc-js/build/src/client.js:160:30)
    at ServiceClientImpl.<anonymous> (/app/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at /app/node_modules/@google-cloud/spanner/build/src/v1/spanner_client.js:214:29
    at /app/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16
    at repeat (/app/node_modules/google-gax/build/src/normalCalls/retries.js:80:25)
    at /app/node_modules/google-gax/build/src/normalCalls/retries.js:118:13
    at OngoingCall.call (/app/node_modules/google-gax/build/src/call.js:67:27)
    at NormalApiCaller.call (/app/node_modules/google-gax/build/src/normalCalls/normalApiCaller.js:34:19)
    at /app/node_modules/google-gax/build/src/createApiCall.js:81:30
```

### PR DESCRIPTION
**Pull request by surbhigarg92**
Fixes #1808

### CODE REVIEW

File: src/partial-result-stream.ts [hunk 1]
```diff
@@ -559,6 +559,8 @@ function isRetryableInternalError(err: grpc.ServiceError): boolean {
     (err.message.includes(
       'Received unexpected EOS on DATA frame from server'
     ) ||
-      err.message.includes('Received RST_STREAM'))
+      err.message.includes('RST_STREAM') ||
+      err.message.includes('HTTP/2 error code: INTERNAL_ERROR') ||
+      err.message.includes('Connection closed with unknown cause'))
```
Comment (olavloite) [inline src/partial-result-stream.ts:564]: Is it not possible to use the `isRetryableInternalError` here?

**Review by olavloite — APPROVED** [review]
LGTM, but with a small nit/question on why we are not using the generic method for the streaming function.

File: src/partial-result-stream.ts (hunk 1 above)
Comment (surbhigarg92) [reply src/partial-result-stream.ts]: Done

**Review by asthamohta — APPROVED** [review]
