### PR TITLE
fix: prevent unhandled promise rejection while projectId or credential not found

### LINKED ISSUE #1333: prevent unhandled promise rejection while default credentials and projectId not set
In case of Project Id or default credential not set it throws the unhandled promise rejection.

### PR DESCRIPTION
**Pull request by laljikanjareeya**
Fixes #1333

### CODE REVIEW

File: src/session-pool.ts [hunk 1]
```diff
@@ -262,6 +262,36 @@ export function isCreateSessionPermissionError(
...
+  error: grpc.ServiceError | undefined
+): boolean {
+  return (
+    error !== undefined &&
+    error.message.includes('Could not load the default credentials')
+  );
+}
+
+/**
+ * Checks whether the given error is a 'Project Id not set in Environment' error.
```
Comment (olavloite) [inline src/session-pool.ts:280]: nit: could we make the error description in the comment correspond with the one that is actually being tested in the method?

**Review by olavloite — APPROVED** [review]
This seems good to me, but it seems that the CI environment is broken at the moment. There's a lot of (I think) unrelated build errors at the moment. I assume that the tests are green locally(?)

**Review by AVaksman — APPROVED** [review]

**Comment by laljikanjareeya** [comment]
> This seems good to me, but it seems that the CI environment is broken at the moment. There's a lot of (I think) unrelated build errors at the moment. I assume that the tests are green locally(?)

Yes All the tests are green locally.

File: src/session-pool.ts (hunk 1 above)
Comment (laljikanjareeya) [reply src/session-pool.ts:280]: `Project Id not set in Environment` is actual message getting while Project Id is not set in environment.

Comment (olavloite) [reply src/session-pool.ts:280]: Then the check below is wrong, because that one reads:

```typescript
    error.message.includes(
      'Unable to detect a Project Id in the current environment'
    )
```

Comment (laljikanjareeya) [reply src/session-pool.ts:280]: @olavloite  my bad below is the actual message getting while project Id or credential not set:
1.  `Unable to detect a Project Id in the current environment`
2.  `Could not load the default credentials`

I will make changes in method description accordingly.

Comment (laljikanjareeya) [reply src/session-pool.ts]: Done!!

**Review by olavloite — APPROVED** [review]
