### PR TITLE
fix: transaction runner should not timeout before first attempt

### LINKED ISSUE #786: test 'transaction-runner - should throw a DeadlineError if the timeout is exceeded' seems flaky
The test `transaction-runner - should throw a DeadlineError if the timeout is exceeded` seems flaky:

https://source.cloud.google.com/results/invocations/fa1053c0-054c-4f8a-ba0a-a3f5a21d7d74/targets/cloud-devrel%2Fclient-libraries%2Fnodejs%2Fpresubmit%2Fgoogleapis%2Fnodejs-spanner%2Fnode12%2Ftest/log

### PR DESCRIPTION
**Pull request by olavloite**
The transaction runner could timeout before the first transaction attempt had been executed, if a very short timeout value had been set. The transaction runner should always execute at least one transaction attempt before throwing a `DeadlineError`.

Fixes #786.

### CODE REVIEW

File: src/transaction-runner.ts [hunk 1]
```diff
@@ -186,7 +186,9 @@ export abstract class Runner<T> {
 
     let lastError: ServiceError;
 
-    while (Date.now() - start < timeout) {
+    // The transaction runner should always executed at least one attempt before
```
Comment (hengfengli) [inline src/transaction-runner.ts]: a type `should always execute at...`

Comment (olavloite) [reply src/transaction-runner.ts]: Fixed.
