### PR TITLE
docs: fix the broken link and improve jsdocs

### LINKED ISSUE #1378: Undocumented ability to set RequestOptions or CallOptions on many APIs
It is possible to set a Request Priority or a deadline/timeout on some of the RPC calls by passing an Options Object wich contains a Gax CallOptions, and/or a RequestOptions object for example: 
* [Table.insert/update/upsert/replace/delete](https://googleapis.dev/nodejs/spanner/latest/Table.html#deleteRows)
* [Transaction.commit](https://googleapis.dev/nodejs/spanner/latest/Transaction.html#commit)

~But it is not possible to set Priorities or deadlines on any of the APIs which read or Execute SQL queries or DML on the database.~

It is however not documented that it is poissible to set these options on the following APIs. The JSDoc does not mention the parameters.

* [Table.read](https://googleapis.dev/nodejs/spanner/latest/Table.html#read)
* [Transaction.run/runStream](https://googleapis.dev/nodejs/spanner/latest/Transaction.html#run)
* [Transaction.read](https://googleapis.dev/nodejs/spanner/latest/Transaction.html#read)
* [Database.run](https://googleapis.dev/nodejs/spanner/latest/Database.html#run)
* [Database.runPartitionedUpdate](https://googleapis.dev/nodejs/spanner/latest/Database.html#runPartitionedUpdate)

(and probably many others that I couldn't find) 

~It is often much more important to set deadlines and priorities on queries so that a response is either returned in a reasonable time, or the query fails, or that a long running DML operation occurs at a low priority.~

~This is possible by accessing the gRPC API directly, but not though the client libraries. ~

#### Environment details

OS: Debian Rodete (20210511.01.04RD)
node: v12.21.0
npm: 7.5.2
google-gax@2.13.0
grpc/grpc-js@1.3.2
grpc-gcp@0.3.3

### PR DESCRIPTION
**Pull request by laljikanjareeya**
Fixes #1378

### CODE REVIEW

File: src/table.ts [hunk 1]
```diff
@@ -426,19 +426,6 @@ class Table {
...
-   *     the status of the request.
-   * @property {object} 1 The full API response.
-   */
-  /**
-   * @callback DropTableCallback
-   * @param {?Error} err Request error, if any.
-   * @param {Operation} operation An {@link Operation} object that can be used to
-   *     check the status of the request.
-   * @param {object} apiResponse The full API response.
-   */
```
Comment (skuruppu) [inline src/table.ts:441]: I'm not sure why this is removed.

Comment (laljikanjareeya) [reply src/table.ts:441]: It is been already define at:
https://github.com/googleapis/nodejs-spanner/blob/ca07a9067bd2259a716ed54aa0102e1fff19e891/src/table.ts#L270

Comment (skuruppu) [reply src/table.ts:441]: Thanks for the clarification.

**Review by skuruppu — APPROVED** [review]
