### PR TITLE
fix: skip some tests when run against the emulator

### LINKED ISSUE #932: Skip some system tests when run against the emulator
We want the system tests to be run against the [Cloud Spanner Emulator](https://cloud.google.com/spanner/docs/emulator). But it has some limitations so some tests need to be skipped.

### PR DESCRIPTION
**Pull request by skuruppu**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-spanner/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #932 🦕

### CODE REVIEW

**Comment by hengfengli** [comment]
Hi @AVaksman, @bcoe, do you have any idea why `ci/windows` fails? I can see it also fails in another PR for the same reason: https://github.com/googleapis/nodejs-spanner/pull/931

**Comment by hengfengli** [comment]
@skuruppu I have skipped all needed tests and fixed related errors. I am not sure: 

1) why "ci / windows" fails. It happens in other PRs as well. 
2) Who should I assign this as a reviewer? I guess you're the PR creator and I can't assign it to you.

File: system-test/spanner.ts [hunk 1]
```diff
@@ -64,6 +64,10 @@ describe('Spanner', () => {
     },
   };
 
+  let emulatorEnabled: string | undefined;
+
+  beforeEach(() => (emulatorEnabled = process.env.SPANNER_EMULATOR_HOST));
```
Comment (stephenplusplus) [inline system-test/spanner.ts:69]: This check should be able to be set outside of a `before`/`beforeEach` block. And just to be a little more accurate with the var name's meaning, can we convert this value to a boolean?:

```ts
describe('Spanner', () => {
  const IS_EMULATOR_ENABLED = typeof process.env.SPANNER_EMULATOR_HOST !== 'undefined';
```

File: system-test/spanner.ts [hunk 2]
```diff
@@ -1051,13 +1070,23 @@ describe('Spanner', () => {
     });
 
     after(async () => {
-      await restoreDatabase.delete();
```
Comment (stephenplusplus) [inline system-test/spanner.ts:1054]: Would doing this here work:?

```ts
if (emulatorEnabled) {
  this.skip();
}
```

Comment (hengfengli) [reply system-test/spanner.ts:1054]: This doesn't work. I tried this at the beginning.

Comment (hengfengli) [reply system-test/spanner.ts:1054]: I got the following error: 

```bash
     Error: `this.skip` forbidden
```

File: system-test/spanner.ts (hunk 1 above)
Comment (hengfengli) [reply system-test/spanner.ts]: Done.

File: system-test/spanner.ts (hunk 2 above)
Comment (skuruppu) [reply system-test/spanner.ts:1054]: I did some research. The [documentation](https://mochajs.org/#inclusive-tests) says to just do a `return` instead of a `skip`. I updated the code.

Comment (hengfengli) [reply system-test/spanner.ts:1054]: Good catch. Thanks for making this more elegant.

**Comment by hengfengli** [comment]
@skuruppu I think we need to clean up the leftover instances in the GCP project. It fails to add a new instance.

**Comment by skuruppu** [comment]
I agree, it's weird though because the tests actually try to clean up the instances before it creates a new one. I'm not sure why that's not working. I suppose it's because we try to [create an instance](https://github.com/googleapis/nodejs-spanner/blob/43765d83d2835eda78a144e4139703e62c4a2266/samples/system-test/spanner.test.js#L132) before deleting the old ones?

**Comment by hengfengli** [comment]
I guess the instance ID is generated by date: 

```ts
const INSTANCE_ID = process.env.SPANNERTEST_INSTANCE || `test-instance-${date}`;
```

The old one from yesterday is not deleted.

**Comment by skuruppu** [comment]
I created #955, let's see if it runs.
