### PR TITLE
fix: update DELETE samples to match docs

### LINKED ISSUE #1071: Update the spanner_delete_data code sample to have examples for all the delete methods
The [Deleting rows in a table](https://cloud.google.com/spanner/docs/modify-mutation-api#python_2) section states:

Each client library provides multiple ways to delete rows:
- Delete all the rows in a table.
- Delete a single row by specifying the key column values for the row.
- Delete a group of rows by creating a key range.
- Delete rows in an interleaved table by deleting the parent rows, if the interleaved table includes ON DELETE CASCADE in its schema definition.

Node.js (and most languages) don't give examples of all of these methods.

### PR DESCRIPTION
**Pull request by skuruppu**
[Docs](https://cloud.google.com/spanner/docs/modify-mutation-api#deleting_rows_in_a_table) list a set of dot points on the multiple ways to perform deletes. The updated samples now contain these examples.

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-spanner/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #1071 🦕

### CODE REVIEW

File: samples/crud.js [hunk 1]
```diff
@@ -134,19 +134,57 @@ async function deleteData(instanceId, databaseId, projectId) {
...
+  // Deletes remaining rows from the Singers table and the Albums table,
+  // because Albums table is defined with ON DELETE CASCADE.
+  database.runTransaction(async (err, transaction) => {
+    if (err) {
+      console.error(err);
+      return;
+    }
+    try {
+      const [rowCount] = await transaction.runUpdate({
+        sql: 'DELETE FROM Singers WHERE true',
```
Comment (olavloite) [inline samples/crud.js:177]: Maybe we should add a comment here on why the `WHERE true` clause is added to the statement.

Comment (skuruppu) [reply samples/crud.js:180]: Good idea. Done.
