### PR TITLE
fix: retry executeStreamingSql when error code is retryable

### LINKED ISSUE #620: 14 UNAVAILABLE: GOAWAY received
#### Environment details

  - OS: Linux
  - Node.js version: 10
  - yarn version: 1.15
  - `@google-cloud/spanner` version: 3.1.0

#### Steps to reproduce

  1. Run a web service using nodejs-spanner
  2. Observe random 14 UNAVAILABLE: GOAWAY errors

It happens 1-5 times a day

The full stacktrace is 
```
14 UNAVAILABLE: GOAWAY received Error: 14 UNAVAILABLE: GOAWAY received
    at Object.exports.createStatusError (/app/node_modules/grpc/src/common.js:91:15)
    at ClientReadableStream._emitStatusIfDone (/app/node_modules/grpc/src/client.js:233:26)
    at ClientReadableStream._receiveStatus (/app/node_modules/grpc/src/client.js:211:8)
    at Object.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:1272:15)
    at InterceptingListener._callNext (/app/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:618:8)
    at Object.onReceiveStatus (/app/node_modules/grpc-gcp/build/src/index.js:93:25)
    at InterceptingListener._callNext (/app/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:618:8)
    at /app/node_modules/grpc/src/client_interceptors.js:1029:24
```

Interestingly, we had a very similar error (`13 INTERNAL: GOAWAY`) when using node-spanner v2.x. We were hoping to see this error disappear by upgrading, which it did, but it apparently got replaced by this one ^^

It might be related to https://github.com/googleapis/nodejs-spanner/issues/234 or to any of these issues https://github.com/grpc/grpc-node/issues?utf8=%E2%9C%93&q=is%3Aissue+GOAWAY+

### PR DESCRIPTION
**Pull request by olavloite**
The streaming call executeStreamingSql is not automatically retried by gax, as the gapic configuration for the call does not specify any error codes that should automatically be retried. Instead, the PartialResultStream is responsible for retrying these calls with the appropriate resume token. Until now, the call was only retried when a valid resume token had been seen for the stream, meaning that if the initial call failed with a retryable error code (e.g. UNAVAILABLE), the
stream would fail with this error. This fix ensures that the call is also retried when the error occurs for the initial call or before the stream has returned a valid resume token.

See also https://github.com/googleapis/nodejs-spanner/blob/09b5c56ed7844514283754235f7203364f01d6ab/test/spanner.ts#L199 for additional tests for retrying streaming errors.

Fixes #620.

### CODE REVIEW

File: src/partial-result-stream.ts [hunk 1]
```diff
@@ -355,13 +359,25 @@ export function partialResultStream(
...
+    if (lastErr) {
+      setImmediate(() => requestsStream.end());
+    }
+  };
   const makeRequest = (): void => {
-    requestsStream.add(requestFn(lastResumeToken));
+    if (lastRequestStream) {
+      lastRequestStream.removeListener('end', endListener);
+    }
+    lastRequestStream = requestFn(lastResumeToken);
```
Comment (hengfengli) [inline src/partial-result-stream.ts]: I wonder if a retryable error happens at an initial call, `lastResumeToken` is empty here, so what would `lastRequestStream` be here? In other words, what will `requestFn` return for an empty `lastResumeToken`?

File: src/partial-result-stream.ts [hunk 2]
```diff
@@ -355,13 +359,25 @@ export function partialResultStream(
     },
   });
 
+  // This listener ensures that the last request that executed successfully
+  // after one or more retries will end the requestsStream.
+  const endListener = () => {
+    if (lastErr) {
+      setImmediate(() => requestsStream.end());
```
Comment (hengfengli) [inline src/partial-result-stream.ts]: I don't quite understand this. Why do we need to do this? `endListener` is triggered by an `end` event in `lastRequestStream`, which means this request is successfully executed. Then, we can close the entire `requestsStream` (a merged stream). Why don't we need to close `requestsStream` in the previous code but now we do?

File: src/partial-result-stream.ts [hunk 3]
```diff
@@ -355,13 +359,25 @@ export function partialResultStream(
     },
   });
 
+  // This listener ensures that the last request that executed successfully
+  // after one or more retries will end the requestsStream.
+  const endListener = () => {
+    if (lastErr) {
```
Comment (hengfengli) [inline src/partial-result-stream.ts]: Currently, `lastErr` includes retryable and non-retryable errors. Shouldn't `lastErr` just be retryable errors?

File: test/partial-result-stream.ts [hunk 4]
```diff
@@ -251,7 +253,60 @@ describe('PartialResultStream', () => {
...
+            message: 'Error.',
+          } as ServiceError);
+          firstFakeRequestStream.end();
+        }, 50);
+
+        return firstFakeRequestStream;
+      });
+
+      requestFnStub.onCall(1).callsFake(resumeToken => {
+        assert.ok(!resumeToken, 'Retry called with resume token');
```
Comment (hengfengli) [inline test/partial-result-stream.ts]: ... with `empty` resume token?

File: src/partial-result-stream.ts (hunk 1 above)
Comment (olavloite) [reply src/partial-result-stream.ts]: This code is also used for the initial call to `requestStreamingSql`, which is also always called without a resume token. Calling `requestFn` another time without a resume token will start a new stream. So:
* The first time this is called (the initial call), `lastRequestStream` is `undefined` at first (i.e. the condition of the `if` statement will be `false`).
* If the initial call fails with a retryable error, this method is called again with `lastRequestStream` still pointing to the initial stream. The `endListener` will then be removed from the initial call and placed on the second call.

File: src/partial-result-stream.ts (hunk 2 above)
Comment (olavloite) [reply src/partial-result-stream.ts]: Yes, this was the part that took me hours to figure out as well. The basic answer is: The original solution seems to never have worked as intended in the first place.

The problem is that the first request stream that causes an error will never indicate to the merged `requestsStream` that it has ended. This can be illustrated with the following test case (not added to the code, as this test case will actually fail):

```typescript
    it('should end merged stream', done => {
      // This test case will never finish when this flag is set to true.
      const simulateRetryAfterError = true;
      const mergedStream = mergeStream();

      eventsIntercept.patch(mergedStream);
      // tslint:disable-next-line no-any
      (mergedStream as any).intercept('error', err => {
        // By intercepting the error, the underlying input stream that caused
        // the error will never end. That in turn will cause the merged stream
        // also to never end.
        console.log('intercepted error');
      });

      const inputStream1 = new Readable();
      inputStream1._read = (size: number): void => {
        setImmediate(() => {
          inputStream1.emit('data', 'one');
          inputStream1.emit('data', 'two');
          // inputStream1.emit('end'); // Uncomment this line and comment out the next line to make the test case work.
          inputStream1.emit('error', new Error('test error'));
        });
      };
      inputStream1.on('end', () => console.log('Input stream 1 ended'));
      if (simulateRetryAfterError) {
        // Add a stream that ends with an error. That error is then intercepted by the merged
        // stream, which causes the merged stream to think that the underlying
        // stream has never ended, which in turn prevents the mergedStream from
        // finishing.
        mergedStream.add(inputStream1);
      }

      const inputStream2 = new Readable();
      inputStream2._read = (size: number): void => {
        setImmediate(() => {
          inputStream2.emit('data', 'three');
          inputStream2.emit('data', 'four');
          inputStream2.emit('end');
        });
      };
      inputStream2.on('end', () => console.log('Input stream 2 ended'));
      mergedStream.add(inputStream2);
      mergedStream.on('finish', () => {
        console.log('merged stream ended');
        done();
      });
    });
```

What basically happens in the above example and also in the `PartialResultStream` in case of a retry is the following:
1. An initial request stream is opened (`inputStream1`) and added to the merged result stream.
2. `inputStream1` emits a retryable error. This error bubbles up to the merged stream, which intercepts it and executes a retry. Intercepting this error means that the mergedStream does not know that `inputStream1` ended with an error, and it erroneously thinks it should still receive data from it.
3. `inputStream2` is started, returns its data and then finishes. The 'end' event bubbles up to the merged stream, but that does not end the merged stream as it is still waiting for input from `inputStream1`.

The above also happened when testing `PartialResultStream` with the mock server. If you remove this `endListener` that was added, you will see that retrying errors does not actually work as intended: All data is returned to the user stream, but the stream is never ended, causing the test cases to hang.

The above example can be made to work by setting `simulateRetryAfterError = false` or by replacing the error from `inputStream1` with an end event for the input stream.

File: src/partial-result-stream.ts (hunk 3 above)
Comment (olavloite) [reply src/partial-result-stream.ts]: Yes, that's true. We don't need it for non-retryable errors. Fixed.

**Comment by alexander-fenster** [comment]
Just one question: since

> as the gapic configuration for the call does not specify any error codes that should automatically be retried

should we talk to API team to reconsider this?

File: src/partial-result-stream.ts [hunk 5]
```diff
@@ -379,7 +398,9 @@ export function partialResultStream(
 
   // need types for events-intercept
   // tslint:disable-next-line no-any
-  (requestsStream as any).intercept('error', retry);
+  (requestsStream as any).intercept('error', err => {
```
Comment (hengfengli) [inline src/partial-result-stream.ts]: nits: probably better to keep the original one. No need to change the code here.

File: src/partial-result-stream.ts (hunk 2 above)
Comment (hengfengli) [reply src/partial-result-stream.ts]: Thanks for the detailed explanation :clap:. This means when an error happens in `inputStream1`, it will emit an `error` event, but there is no `end` event after that. The merged stream is not ended, so it will not emit `finish` event.

File: test/partial-result-stream.ts [hunk 6]
```diff
@@ -251,7 +253,63 @@ describe('PartialResultStream', () => {
...
+      const requestFnStub = sandbox.stub();
+
+      requestFnStub.onCall(0).callsFake(() => {
+        setTimeout(() => {
+          // This causes a new request stream to be created.
+          firstFakeRequestStream.emit('error', {
+            code: status.UNAVAILABLE,
+            message: 'Error.',
+          } as ServiceError);
+          firstFakeRequestStream.end();
```
Comment (hengfengli) [inline test/partial-result-stream.ts]: In order to simulate the real case as we discussed, I think we should remove this. I tried it and it works fine.

File: test/partial-result-stream.ts [hunk 7]
```diff
@@ -309,6 +370,50 @@ describe('PartialResultStream', () => {
...
+          fakeCheckpointStream.emit('checkpoint', RESULT_WITH_TOKEN);
+          fakeRequestStream.push(RESULT_WITH_TOKEN);
+          fakeCheckpointStream.emit('checkpoint', RESULT_WITH_TOKEN);
+
+          setTimeout(() => {
+            fakeRequestStream.emit('error', {
+              code: status.DATA_LOSS,
+              message: 'Non-retryable error.',
+            } as ServiceError);
+            fakeRequestStream.end();
```
Comment (hengfengli) [inline test/partial-result-stream.ts]: Same above. It can be deleted.

File: test/partial-result-stream.ts [hunk 8]
```diff
@@ -276,7 +334,10 @@ describe('PartialResultStream', () => {
 
           setTimeout(() => {
             // This causes a new request stream to be created.
-            firstFakeRequestStream.emit('error', new Error('Error.'));
+            firstFakeRequestStream.emit('error', {
+              code: status.UNAVAILABLE,
+              message: 'Error.',
+            } as ServiceError);
             firstFakeRequestStream.end();
```
Comment (hengfengli) [inline test/partial-result-stream.ts]: Same above.

File: src/partial-result-stream.ts (hunk 2 above)
Comment (hengfengli) [reply src/partial-result-stream.ts]: FYI, when I changed your test case from `finish` to `end`, like this: 

```typescript
      mergedStream.on('end', () => {
        console.log('merged stream ended');
        done();
      });
```

I commented the error and uncommented the `end`: 

```typescript
          ...
          inputStream1.emit('end'); // Uncomment this line and comment out the next line to make the test case work.
          // inputStream1.emit('error', new Error('test error'));
          ...
```

This does not work any more. I was wondering why this happens, :sweat_smile:. Then, I found this link: https://nodejs.org/api/stream.html#stream_events_finish_and_end.

**Comment by olavloite** [comment]
> Just one question: since
> 
> > as the gapic configuration for the call does not specify any error codes that should automatically be retried
> 
> should we talk to API team to reconsider this?

That is certainly an option, but it is something that we in that case should do in sync with all client libraries. I know that the Java and Go client libraries also have custom implementations that retry UNAVAILABLE errors for the executeStreamingSql RPC, and I assume that it is also the case of other languages.

File: test/partial-result-stream.ts (hunk 7 above)
Comment (olavloite) [reply test/partial-result-stream.ts]: `end()` call removed from test case.

In case of a non-retryable error, we circumvent the `requestsStream` and send an error directly to the stream that is returned to the user (technically, by sending it first to the `batchAndSplitOnTokenStream`). So it is not necessary to end the `requestsStream` in that case.

See https://github.com/googleapis/nodejs-spanner/blob/569570fe3ed7a8ebc10b0ed2d528435102be5e82/src/partial-result-stream.ts#L383

File: src/partial-result-stream.ts (hunk 5 above)
Comment (olavloite) [reply src/partial-result-stream.ts]: Done.

File: test/partial-result-stream.ts (hunk 6 above)
Comment (olavloite) [reply test/partial-result-stream.ts]: Done

File: test/partial-result-stream.ts (hunk 8 above)
Comment (olavloite) [reply test/partial-result-stream.ts]: Done.

File: src/partial-result-stream.ts (hunk 2 above)
Comment (olavloite) [reply src/partial-result-stream.ts]: > Thanks for the detailed explanation . This means when an error happens in `inputStream1`, it will emit an `error` event, but there is no `end` event after that. The merged stream is not ended, so it will not emit `finish` event.

Correct. And the error that is emitted by `inputStream1` is intercepted, so that also keeps the merged stream think that `inputStream1` is still alive.
